name: 'Photographer & Videographer in Dubrovnik'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.33895
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-44420882-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d3d3d3'
    - '#b5b5b5'
    - '#141414'
    - '#666666'
    - '#fbfbfb'
  brandStrength: 1
  lightness: 0.125
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
