name: 'Photographer & Videographer in Dubrovnik'
favicon: null
layout_spectrum: 0.9404587086755782
typography_spectrum: 0.757014992646873
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-44420882-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.9923612575512379
  lightness: 0.5203136631753296
  saturation: 0.8912377953529358
  rhythmicContrast: 0.6886592442169785
purpose: []
