name: 'Photographer & Videographer in Dubrovnik'
favicon: null
layout_spectrum: 0.9404587086755782
typography_spectrum: 0.757014992646873
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-44420882-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#ff9400'
    - '#ff5200'
    - '#a96b31'
    - '#ca341b'
  brandStrength: 0.9923612575512379
  lightness: 0.5203136631753296
  saturation: 0.8912377953529358
  rhythmicContrast: 0.6886592442169785
purpose: []
